name = "dotvocab"
main = "src/index.ts"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "dotvocab"
database_id = "a2babb4b-9845-4197-8e8a-bc2b30979008"
