-- dotVocab seed: 三年级上(沪教新版)
-- generated; idempotent (INSERT OR IGNORE)

INSERT OR IGNORE INTO units (book, unit, sort_key) VALUES ('三年级上(沪教新版)', 'Unit 1', 1);
INSERT OR IGNORE INTO units (book, unit, sort_key) VALUES ('三年级上(沪教新版)', 'Unit 2', 2);
INSERT OR IGNORE INTO units (book, unit, sort_key) VALUES ('三年级上(沪教新版)', 'Unit 3', 3);
INSERT OR IGNORE INTO units (book, unit, sort_key) VALUES ('三年级上(沪教新版)', 'Unit 4', 4);
INSERT OR IGNORE INTO units (book, unit, sort_key) VALUES ('三年级上(沪教新版)', 'Unit 5', 5);
INSERT OR IGNORE INTO units (book, unit, sort_key) VALUES ('三年级上(沪教新版)', 'Unit 6', 6);
INSERT OR IGNORE INTO units (book, unit, sort_key) VALUES ('三年级上(沪教新版)', 'Unit 7', 7);
INSERT OR IGNORE INTO units (book, unit, sort_key) VALUES ('三年级上(沪教新版)', 'Unit 8', 8);
INSERT OR IGNORE INTO units (book, unit, sort_key) VALUES ('三年级上(沪教新版)', 'Unit 9', 9);
INSERT OR IGNORE INTO units (book, unit, sort_key) VALUES ('三年级上(沪教新版)', 'Unit 10', 10);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('new', NULL, '新的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('school', NULL, '学校', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('classmate', NULL, '同班同学', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('teacher', NULL, '教师;老师', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('play sports', NULL, '运动', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('read', NULL, '阅读', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('book', NULL, '书', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('study', NULL, '学习;研读', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('hard', NULL, '努力地', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('goal', NULL, '目标;目的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('want', NULL, '要;想要', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('friend', NULL, '朋友', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('plan', NULL, '计划;打算', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('follow', NULL, '跟随;跟着', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('start', NULL, '开始;起点', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('be good at', NULL, '擅长于', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('draw', NULL, '画画', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('tell a story', NULL, '讲故事', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('dance', NULL, '跳舞', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('player', NULL, '运动员', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('run', NULL, '跑;奔跑', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('cool', NULL, '妙极的;酷的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('fly high', NULL, '飞得很高', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('jump', NULL, '跳;跳跃', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('be proud of', NULL, '为....自豪', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('rabbit', NULL, '兔子', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('walk', NULL, '走;行走', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('umbrella', NULL, '伞', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('use the computer', NULL, '使用电脑', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('garden', NULL, '花园;果园;菜园', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('welcome', NULL, '欢迎', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('open', NULL, '开;打开', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('close', NULL, '关;关闭', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('flower', NULL, '花', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('vegetable', NULL, '蔬菜', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('plant', NULL, '植物', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('beautiful', NULL, '美丽的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('see', NULL, '看见;见到', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('orange tree', NULL, '橘子树', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('tomato', NULL, '番茄;西红柿', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('place', NULL, '位置;地点', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('carrot', NULL, '胡萝卜', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('leaf', NULL, '叶子', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('water', NULL, '给...浇水；水', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('grandpa', NULL, '外公;爷爷', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('grow', NULL, '(使)生长', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('grandma', NULL, '外婆;奶奶', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('tea', NULL, '茶', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('strawberries', NULL, '草莓', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('cloud', NULL, '云;云朵', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('find', NULL, '发现', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('river', NULL, '河;江', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('lake', NULL, '湖;湖泊', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('sea', NULL, '海;海洋', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('water vapour', NULL, '水蒸气', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('from', NULL, '从…起;来自', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('little by little', NULL, '缓慢地;一点一点地', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('become', NULL, '变成', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('rain', NULL, '雨;雨水', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('snow', NULL, '雪', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('ice', NULL, '冰', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('where', NULL, '在哪里;到哪里', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('cold', NULL, '寒冷的;冷的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('when', NULL, '什么时候;何时', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('hot', NULL, '温度高的;热的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('drops', NULL, '水珠；水滴', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('help', NULL, '帮助', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('chore', NULL, '日常事务', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('busy', NULL, '忙碌的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('cook', NULL, '烹饪;烹调', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('do the dishes', NULL, '洗碗碟', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('young', NULL, '幼小的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('small', NULL, '小的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('clothes', NULL, '衣服', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('toy', NULL, '玩具', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('clean the table', NULL, '擦桌子', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('drink water', NULL, '喝水', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('fall', NULL, '掉落;跌落', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('drop', NULL, '使落下', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('old', NULL, '旧的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('walk the dog', NULL, '遛狗', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('seat', NULL, '座位', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('delicious', NULL, '美味的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('fox', NULL, '狐狸', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('ant', NULL, '蚂蚁', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('give your seat', NULL, '让座', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('feel', NULL, '觉得;感到', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('sometimes', NULL, '有时', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('happy', NULL, '快乐的;高兴的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('sad', NULL, '悲哀的;难过的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('good', NULL, '令人愉快的;好的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('happen', NULL, '(偶然)发生', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('excited', NULL, '激动的;兴奋的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('but', NULL, '但是;而;相反', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('scared', NULL, '害怕的;恐惧的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('tired', NULL, '疲倦的;疲劳的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('come', NULL, '来', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('big wheel', NULL, '摩天轮', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('sign', NULL, '标志；标牌', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('unhappy', NULL, '不快乐;悲伤的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('bad', NULL, '令人不快的;坏的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('job', NULL, '工作;职业', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('driver', NULL, '驾驶员;司机', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('careful', NULL, '小心的;谨慎的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('police officer', NULL, '警察;警员', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('dream', NULL, '梦想;理想', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('engineer', NULL, '工程师;设计师', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('author', NULL, '作家;作者', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('doctor', NULL, '医生;大夫', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('chef', NULL, '厨师', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('astronaut', NULL, '宇航员;航天员', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('spaceship', NULL, '(航天)飞船', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('difficult', NULL, '困难的;难做的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('skill', NULL, '技巧;技艺', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('space', NULL, '太空', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('library', NULL, '图书馆', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('there', NULL, '在那里;到那里', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('find the way', NULL, '找到路', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('parent', NULL, '父亲或母亲', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('get to', NULL, '到达', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('walk along', NULL, '沿着...走', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('road', NULL, '路;道路;公路', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('left', NULL, '左边;向左边', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('right', NULL, '右边;向右边', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('ask...for help', NULL, '请....帮忙', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('excuse me', NULL, '打扰了;劳驾', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('get lost', NULL, '迷路', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('mum', NULL, '妈妈', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('museum', NULL, '博物馆', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('stay', NULL, '停留;待', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('wait for', NULL, '等待', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('phone', NULL, '电话', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('call', NULL, '打电话叫', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('exhibition', NULL, '展览会;展示', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('visit', NULL, '参观；游览', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('special days', NULL, '特别的日子', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('get together', NULL, '团聚;聚会', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('the double ninth festival', NULL, '重阳节', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('celebrate', NULL, '庆祝;庆贺', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('dragon dance', NULL, '舞龙表演', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('climb the mountain', NULL, '爬山', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('miss', NULL, '怀念;思念', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('the lantern festival', NULL, '元宵节', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('chinese new year', NULL, '中国新年', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('holiday', NULL, '假期', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('during', NULL, '在……期间', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('the spring festival', NULL, '春节', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('food', NULL, '食物', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('world', NULL, '世界', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('famous', NULL, '著名的;出名的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('noodle', NULL, '面条', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('pizza', NULL, '比萨饼', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('sandwich', NULL, '三明治', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('hot dog', NULL, '热狗', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('taste', NULL, '品尝;尝出..味道', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('different', NULL, '不同的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('long', NULL, '长的', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('meatball', NULL, '肉丸', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('fish and chips', NULL, '炸鱼薯条', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('beef', NULL, '牛肉', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('bread', NULL, '面包', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('flour', NULL, '（小麦)面粉', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('cake', NULL, '糕饼;蛋糕', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('sausage', NULL, '香肠；腊肠', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO words (term, pos, meaning_cn, example_en, example_cn, created_at) VALUES ('origin', NULL, '起源；源头', NULL, NULL, 1785463633727);
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 1'), (SELECT id FROM words WHERE term='new'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 1'), (SELECT id FROM words WHERE term='school'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 1'), (SELECT id FROM words WHERE term='classmate'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 1'), (SELECT id FROM words WHERE term='teacher'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 1'), (SELECT id FROM words WHERE term='play sports'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 1'), (SELECT id FROM words WHERE term='read'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 1'), (SELECT id FROM words WHERE term='book'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 1'), (SELECT id FROM words WHERE term='study'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 1'), (SELECT id FROM words WHERE term='hard'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 1'), (SELECT id FROM words WHERE term='goal'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 1'), (SELECT id FROM words WHERE term='want'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 1'), (SELECT id FROM words WHERE term='friend'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 1'), (SELECT id FROM words WHERE term='plan'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 1'), (SELECT id FROM words WHERE term='follow'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 1'), (SELECT id FROM words WHERE term='start'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 2'), (SELECT id FROM words WHERE term='be good at'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 2'), (SELECT id FROM words WHERE term='draw'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 2'), (SELECT id FROM words WHERE term='tell a story'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 2'), (SELECT id FROM words WHERE term='dance'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 2'), (SELECT id FROM words WHERE term='player'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 2'), (SELECT id FROM words WHERE term='run'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 2'), (SELECT id FROM words WHERE term='cool'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 2'), (SELECT id FROM words WHERE term='fly high'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 2'), (SELECT id FROM words WHERE term='jump'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 2'), (SELECT id FROM words WHERE term='be proud of'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 2'), (SELECT id FROM words WHERE term='rabbit'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 2'), (SELECT id FROM words WHERE term='walk'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 2'), (SELECT id FROM words WHERE term='umbrella'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 2'), (SELECT id FROM words WHERE term='use the computer'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 3'), (SELECT id FROM words WHERE term='garden'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 3'), (SELECT id FROM words WHERE term='welcome'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 3'), (SELECT id FROM words WHERE term='open'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 3'), (SELECT id FROM words WHERE term='close'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 3'), (SELECT id FROM words WHERE term='flower'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 3'), (SELECT id FROM words WHERE term='vegetable'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 3'), (SELECT id FROM words WHERE term='plant'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 3'), (SELECT id FROM words WHERE term='beautiful'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 3'), (SELECT id FROM words WHERE term='see'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 3'), (SELECT id FROM words WHERE term='orange tree'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 3'), (SELECT id FROM words WHERE term='tomato'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 3'), (SELECT id FROM words WHERE term='place'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 3'), (SELECT id FROM words WHERE term='carrot'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 3'), (SELECT id FROM words WHERE term='leaf'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 3'), (SELECT id FROM words WHERE term='water'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 3'), (SELECT id FROM words WHERE term='grandpa'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 3'), (SELECT id FROM words WHERE term='grow'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 3'), (SELECT id FROM words WHERE term='grandma'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 3'), (SELECT id FROM words WHERE term='tea'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 3'), (SELECT id FROM words WHERE term='strawberries'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 4'), (SELECT id FROM words WHERE term='water'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 4'), (SELECT id FROM words WHERE term='cloud'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 4'), (SELECT id FROM words WHERE term='find'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 4'), (SELECT id FROM words WHERE term='river'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 4'), (SELECT id FROM words WHERE term='lake'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 4'), (SELECT id FROM words WHERE term='sea'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 4'), (SELECT id FROM words WHERE term='water vapour'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 4'), (SELECT id FROM words WHERE term='from'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 4'), (SELECT id FROM words WHERE term='little by little'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 4'), (SELECT id FROM words WHERE term='become'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 4'), (SELECT id FROM words WHERE term='rain'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 4'), (SELECT id FROM words WHERE term='snow'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 4'), (SELECT id FROM words WHERE term='ice'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 4'), (SELECT id FROM words WHERE term='where'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 4'), (SELECT id FROM words WHERE term='cold'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 4'), (SELECT id FROM words WHERE term='when'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 4'), (SELECT id FROM words WHERE term='hot'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 4'), (SELECT id FROM words WHERE term='drops'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 5'), (SELECT id FROM words WHERE term='help'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 5'), (SELECT id FROM words WHERE term='chore'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 5'), (SELECT id FROM words WHERE term='busy'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 5'), (SELECT id FROM words WHERE term='cook'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 5'), (SELECT id FROM words WHERE term='do the dishes'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 5'), (SELECT id FROM words WHERE term='young'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 5'), (SELECT id FROM words WHERE term='small'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 5'), (SELECT id FROM words WHERE term='clothes'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 5'), (SELECT id FROM words WHERE term='toy'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 5'), (SELECT id FROM words WHERE term='clean the table'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 5'), (SELECT id FROM words WHERE term='drink water'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 5'), (SELECT id FROM words WHERE term='fall'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 5'), (SELECT id FROM words WHERE term='drop'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 5'), (SELECT id FROM words WHERE term='old'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 5'), (SELECT id FROM words WHERE term='walk the dog'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 5'), (SELECT id FROM words WHERE term='seat'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 5'), (SELECT id FROM words WHERE term='delicious'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 5'), (SELECT id FROM words WHERE term='fox'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 5'), (SELECT id FROM words WHERE term='ant'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 5'), (SELECT id FROM words WHERE term='give your seat'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 6'), (SELECT id FROM words WHERE term='feel'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 6'), (SELECT id FROM words WHERE term='sometimes'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 6'), (SELECT id FROM words WHERE term='happy'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 6'), (SELECT id FROM words WHERE term='sad'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 6'), (SELECT id FROM words WHERE term='good'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 6'), (SELECT id FROM words WHERE term='happen'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 6'), (SELECT id FROM words WHERE term='excited'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 6'), (SELECT id FROM words WHERE term='but'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 6'), (SELECT id FROM words WHERE term='scared'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 6'), (SELECT id FROM words WHERE term='tired'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 6'), (SELECT id FROM words WHERE term='come'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 6'), (SELECT id FROM words WHERE term='big wheel'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 6'), (SELECT id FROM words WHERE term='sign'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 6'), (SELECT id FROM words WHERE term='unhappy'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 6'), (SELECT id FROM words WHERE term='bad'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 7'), (SELECT id FROM words WHERE term='job'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 7'), (SELECT id FROM words WHERE term='driver'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 7'), (SELECT id FROM words WHERE term='careful'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 7'), (SELECT id FROM words WHERE term='police officer'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 7'), (SELECT id FROM words WHERE term='dream'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 7'), (SELECT id FROM words WHERE term='engineer'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 7'), (SELECT id FROM words WHERE term='author'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 7'), (SELECT id FROM words WHERE term='doctor'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 7'), (SELECT id FROM words WHERE term='chef'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 7'), (SELECT id FROM words WHERE term='astronaut'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 7'), (SELECT id FROM words WHERE term='spaceship'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 7'), (SELECT id FROM words WHERE term='difficult'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 7'), (SELECT id FROM words WHERE term='skill'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 7'), (SELECT id FROM words WHERE term='study'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 7'), (SELECT id FROM words WHERE term='space'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 8'), (SELECT id FROM words WHERE term='library'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 8'), (SELECT id FROM words WHERE term='there'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 8'), (SELECT id FROM words WHERE term='find the way'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 8'), (SELECT id FROM words WHERE term='parent'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 8'), (SELECT id FROM words WHERE term='get to'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 8'), (SELECT id FROM words WHERE term='walk along'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 8'), (SELECT id FROM words WHERE term='road'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 8'), (SELECT id FROM words WHERE term='left'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 8'), (SELECT id FROM words WHERE term='right'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 8'), (SELECT id FROM words WHERE term='ask...for help'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 8'), (SELECT id FROM words WHERE term='excuse me'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 8'), (SELECT id FROM words WHERE term='get lost'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 8'), (SELECT id FROM words WHERE term='mum'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 8'), (SELECT id FROM words WHERE term='museum'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 8'), (SELECT id FROM words WHERE term='stay'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 8'), (SELECT id FROM words WHERE term='wait for'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 8'), (SELECT id FROM words WHERE term='phone'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 8'), (SELECT id FROM words WHERE term='call'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 8'), (SELECT id FROM words WHERE term='exhibition'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 8'), (SELECT id FROM words WHERE term='visit'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 9'), (SELECT id FROM words WHERE term='special days'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 9'), (SELECT id FROM words WHERE term='get together'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 9'), (SELECT id FROM words WHERE term='the double ninth festival'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 9'), (SELECT id FROM words WHERE term='celebrate'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 9'), (SELECT id FROM words WHERE term='dragon dance'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 9'), (SELECT id FROM words WHERE term='climb the mountain'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 9'), (SELECT id FROM words WHERE term='miss'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 9'), (SELECT id FROM words WHERE term='the lantern festival'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 9'), (SELECT id FROM words WHERE term='chinese new year'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 9'), (SELECT id FROM words WHERE term='holiday'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 9'), (SELECT id FROM words WHERE term='during'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 9'), (SELECT id FROM words WHERE term='the spring festival'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 10'), (SELECT id FROM words WHERE term='food'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 10'), (SELECT id FROM words WHERE term='world'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 10'), (SELECT id FROM words WHERE term='famous'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 10'), (SELECT id FROM words WHERE term='noodle'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 10'), (SELECT id FROM words WHERE term='pizza'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 10'), (SELECT id FROM words WHERE term='sandwich'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 10'), (SELECT id FROM words WHERE term='hot dog'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 10'), (SELECT id FROM words WHERE term='taste'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 10'), (SELECT id FROM words WHERE term='different'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 10'), (SELECT id FROM words WHERE term='long'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 10'), (SELECT id FROM words WHERE term='meatball'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 10'), (SELECT id FROM words WHERE term='fish and chips'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 10'), (SELECT id FROM words WHERE term='beef'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 10'), (SELECT id FROM words WHERE term='bread'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 10'), (SELECT id FROM words WHERE term='flour'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 10'), (SELECT id FROM words WHERE term='cake'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 10'), (SELECT id FROM words WHERE term='sausage'));
INSERT OR IGNORE INTO unit_words (unit_id, word_id) VALUES ((SELECT id FROM units WHERE book='三年级上(沪教新版)' AND unit='Unit 10'), (SELECT id FROM words WHERE term='origin'));
